### ISSUE TITLE
同一个局域网内，无法Web端电脑看书

### ISSUE THREAD

**Issue by zhangweildlh** [gedoor/legado_web_bookshelf#55]
电脑端网址：192.168.0.4
手机：192.168.0.102
网关：192.168.0.1
中继是小米路由器：192.168.0.2
网关与小米路由是通过Wifi连接；电脑与小米路由是通过网线连接。

Web端提醒访问失败！
![4](https://user-images.githubusercontent.com/62597291/203697236-c746848f-f174-4a06-8587-fc40a3ee9702.jpg)
![3](https://user-images.githubusercontent.com/62597291/203697241-0df3ee92-69be-4c99-a73b-584be3a05275.jpg)
![2](https://user-images.githubusercontent.com/62597291/203697243-1d2e97bb-24fc-48be-8183-29b1e4098ae2.jpg)
![1](https://user-images.githubusercontent.com/62597291/203697244-5b1d5608-4809-40f2-aaf6-3c2c7e48bb20.jpg)

**Comment by zhangweildlh** [comment]
上面是在家测试的。今下午在公司，用局域网又测试了，还是不行。但MT管理器开的FTP可以正常使用。
![微信图片_20221124154638](https://user-images.githubusercontent.com/62597291/203723726-97c5f501-c3e2-4808-9c8e-94c848470320.jpg)
![微信图片_20221124154442](https://user-images.githubusercontent.com/62597291/203723788-c2ecddc2-42ef-44c6-a2fd-cbb7fb555704.png)
![微信图片_20221124154642](https://user-images.githubusercontent.com/62597291/203723817-81e70ef7-be31-4238-9878-72b17cbaac2e.jpg)
![微信截图_20221124154540](https://user-images.githubusercontent.com/62597291/203723838-7d750047-9f3b-41bd-8a02-95a099309acc.png)

**Comment by Xwite** [comment]
在线版本代码已经没有维护了
