### ISSUE TITLE
Wrong narrow media size: @media screen and (max-width: 750px) 

### ISSUE THREAD

**Issue by mozbugbox** [gedoor/legado_web_bookshelf#73]
The threshold of the small screen layout `miniInterface` was set to a wrong value.  Pads with the width around 800px would have both the `tool-bar` and the `read-bar` cutoff the screen.

As can be see in the  code
https://github.com/gedoor/legado_web_bookshelf/blob/81385456111cb9b32165fb9521a59107f83388a5/src/views/Chapter.vue#L218-L224 

The minimal width for a non-miniInterface screen would be `tool-bar` + `chapter` + `read-bar` + 130.  

Since the chapter size is set to 670px, i.e. `68 + 670 + 52 + 130 = 920`. 

Now the screen is symmetrical, the width has to take the `max(tool-bar, read-bar)`. Therefore the minimum width: `68 * 2 + 670 + 130 = 936px`.

The current threshold is set at 750px
https://github.com/gedoor/legado_web_bookshelf/blob/81385456111cb9b32165fb9521a59107f83388a5/src/views/Chapter.vue#L786-L789

**Comment by Xwite** [comment]
run code below in your browser
```js
window.innerWidth
```

**Comment by mozbugbox** [comment]
I used it on an ipad mini, which has a 768x1024 viewport. 

https://yesviz.com/tablets.php

There's still quite a few Pad has viewport with <900 width in portrait view.

**Comment by Xwite** [comment]
fix
