### ISSUE TITLE
为什么我手机一息屏，网页端书架就连接断开了

### ISSUE THREAD

**Issue by myname-dyh** [gedoor/legado_web_bookshelf#76]
手机型号是HUAWEI MATE 50

**Comment by gedoor** [comment]
好像有人提过这个问题,后来找到解决方法了,你翻翻历史issue



***@***.***
 
发件人： myname-dyh
发送时间： 2023-05-19 10:33
收件人： gedoor/legado_web_bookshelf
抄送： Subscribed
主题： [gedoor/legado_web_bookshelf] 为什么我手机一息屏，网页端书架就连接断开了 (Issue #76)
手机型号是HUAWEI MATE 50

**Comment by myname-dyh** [comment]
我这边看一共是有9个issue，6个已关闭，其中相似的一个为“同一个局域网内，无法Web端电脑看书”，但这和我遇到的并不是同一个问题，我在手机亮屏情况下web端可以正常同步和阅读，但是手机息屏之后就无法同步手机端的信息，手机端休眠时始终保持网络连接的功能也是打开着的

**Comment by myname-dyh** [comment]
在手机端issue阅读一章有概率自动暂停找到解决方案，手机设置应用启动管理关闭自动管理，设置为允许后台活动就可以了，看来华为手机使用阅读的一些功能，需要手动设置应用为手动管理
